version: '3.1'

services:

  postgres:
    image: postgres
    restart: always
    ports:
      - 5440:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: support

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080